### ISSUE TITLE
Preview scope dock crashes at exit of OBS Studio

### ISSUE THREAD

**Issue by norihiro** [norihiro/obs-color-monitor#46]
**Describe the bug**
OBS Studio sometimes crashes when exiting.
Back-trace is as below.
```
#0  0x000000e7ca500000 in  ()
#1  0x00007ffff514c5fe in QMetaObject::cast(QObject const*) const () at /lib64/libQt5Core.so.5
#2  0x00007ffff5fcab72 in QListWidget::currentItem() const () at /lib64/libQt5Widgets.so.5
#3  0x000000000049f4c8 in OBSBasic::GetCurrentScene() (this=<optimized out>)
    at /home/user/repo/obs-studio/UI/window-basic-main.cpp:2758
#4  0x0000000000497520 in OBSBasic::GetCurrentSceneSource() (this=<optimized out>)
    at /home/user/repo/obs-studio/UI/window-basic-main.hpp:823
#5  OBSStudioAPI::obs_frontend_get_current_preview_scene() (this=0xcdeca0)
    at /home/user/repo/obs-studio/UI/api-interface.cpp:556
#6  0x00007fff82f3b3a0 in cm_tick (data=data@entry=0x24deb60, unused=<optimized out>)
    at /home/user/repo/obs-color-monitor/src/common.c:303
#7  0x00007fff82f39338 in roi_tick (data=0x24deb60, unused=<optimized out>) at /home/user/repo/obs-color-monitor/src/roi.c:608
#8  0x00007ffff5adda63 in obs_source_video_tick (source=source@entry=0x24da700, seconds=seconds@entry=0.0333333313)
    at /home/user/repo/obs-studio/libobs/obs-source.c:1254
#9  0x00007ffff5b17efe in tick_sources (last_time=<optimized out>, cur_time=906998500555845)
    at /home/user/repo/obs-studio/libobs/obs-video.c:69
#10 obs_graphics_thread_loop (context=context@entry=0x7fff8a5792d0) at /home/user/repo/obs-studio/libobs/obs-video.c:964
#11 0x00007ffff5b19ab0 in obs_graphics_thread (param=<optimized out>) at /home/user/repo/obs-studio/libobs/obs-video.c:1053
#12 0x00007ffff626d299 in start_thread () at /lib64/libpthread.so.0
#13 0x00007ffff4a4e353 in clone () at /lib64/libc.so.6
```

**Your setup**
- Scope Dock whose target is preview
- obs-studio 27.1.3-259-g5df343d2b
- obs-color-monitor 0.2.6-7-g723bdb5

**Additional context**
OBS's log file is here.
https://obsproject.com/logs/d9puDb11ahU9Gkr4

**Comment by norihiro** [comment]
I referred how the source-dock is handling events from the frontend API and followed their implementation. I'm not certain whether the commit really fixes the issue because the crash does not frequently happen.
